import { test, expect } from "@playwright/test";
import { mkdtempSync, rmSync } from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";
import { createApp } from "../server/app.js";

let server, db, base, dir;
test.beforeAll(async () => {
  dir = mkdtempSync(path.join(tmpdir(), "pg-terms-"));
  const result = createApp({ dataDir: dir });
  db = result.db;
  server = result.app.listen(0, "127.0.0.1");
  await new Promise((resolve) => server.once("listening", resolve));
  base = "http://127.0.0.1:" + server.address().port;
});
test.afterAll(async () => {
  await new Promise((resolve) => server.close(resolve));
  db.close();
  rmSync(dir, { recursive: true, force: true });
});

test("glossary search, copy, related terms, insertion, version isolation and mobile", async ({ page, context }) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.goto(base);
  await page.getByLabel("账号", { exact: true }).fill("terms-admin");
  await page.getByLabel("密码", { exact: true }).fill("terms-test-password-123");
  await page.getByRole("button", { name: "创建并进入" }).click();
  await page.getByRole("button", { name: "术语库", exact: true }).click();
  await expect(page.getByText("找到 128 条术语", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "移动端 H5 30", exact: true }).click();
  await expect(page.locator(".term-results > button")).toHaveCount(30);
  const search = page.getByRole("textbox", { name: "搜索术语" });
  await search.fill("SAFE AREA");
  await expect(page.locator(".term-detail h2")).toHaveText("安全区");
  await page.getByRole("button", { name: "复制标准需求表达", exact: true }).click();
  const requirement = await page.locator(".term-say p").innerText();
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(requirement);
  await page.getByRole("button", { name: "吸底操作栏", exact: true }).click();
  await expect(page.locator(".term-detail h2")).toHaveText("吸底操作栏");
  await search.fill("下面那条黑杠");
  await expect(page.locator(".term-detail h2")).toHaveText("安全区");
  await search.fill("no-such-term-xyz");
  await expect(page.getByText("没有找到匹配的术语")).toBeVisible();
  await page.getByRole("button", { name: "重置筛选" }).click();
  await page.getByRole("button", { name: "全部案例" }).click();
  await page.getByRole("button", { name: "新建案例", exact: true }).first().click();
  await page.getByPlaceholder("给这个效果起个名字").fill("术语插入测试");
  await page.getByPlaceholder("如 OpenAI").fill("test");
  await page.getByPlaceholder("输入模型名称").fill("test");
  const prompt = page.getByPlaceholder("记录生成这个效果时使用的提示词…");
  await prompt.fill("原始版本");
  await page.getByRole("button", { name: "新版本", exact: true }).click();
  await prompt.fill("前文\n后文");
  await prompt.press("Control+Home");
  await prompt.press("ArrowDown");
  await page.getByRole("button", { name: "查阅术语", exact: true }).click();
  await page.getByRole("textbox", { name: "搜索术语" }).fill("safe area");
  await page.getByRole("button", { name: "插入提示词", exact: true }).click();
  await expect(prompt).toHaveValue("前文\n" + requirement + "\n后文");
  await expect(page.getByText("有未保存的修改", { exact: true })).toBeVisible();
  await page.getByLabel("版本", { exact: true }).selectOption({ index: 0 });
  await expect(prompt).toHaveValue("原始版本");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.getByText("已保存", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "返回案例库" }).click();
  await page.getByRole("button", { name: "打开术语插入测试", exact: true }).click();
  await page.getByLabel("版本", { exact: true }).selectOption({ index: 1 });
  await expect(prompt).toHaveValue("前文\n" + requirement + "\n后文");
  await page.getByRole("button", { name: "查阅术语", exact: true }).click();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "提示词术语助手" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "查阅术语", exact: true })).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "查阅术语", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "提示词术语助手" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/terms-mobile.png", fullPage: false });
  expect(errors).toEqual([]);
});
